site_name: Sword of Moonlight Â» Compendium
site_url: https://doc.swordofmoonlight.com/
site_description: Documentation for Sword of Moonlight - King's Field Making Tool
site_author: DMPDesign, StolenBattenberg, Verdite Cat
copyright: Licensed under CC BY-SA, please use responsibly.
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - SoM Editor:
    - Parameter Editor:
      - Overview: editor/parameterseditor/overview.md
      - Item: editor/parameterseditor/parameditems.md
    - Content Authoring:
      - Authoring Custom Objects: editor/contentauthoring/auth-object.md
      - Authoring Custom Enemies: editor/contentauthoring/auth-enemy.md
      - Authoring Custom Textures: editor/contentauthoring/auth-texture.md
  - SoM Tools:
    - Lawful Blade:
      - Overview: lawfulblade/lawful-brief.md
      - Installation: lawfulblade/lawful-install.md
      - Configuration: lawfulblade/lawful-preference.md
      - Creating Your First Instance: lawfulblade/lawful-create-instance.md
      - Managing Instance Packages: lawfulblade/lawful-instance-packages.md
      - Creating Your First Project: lawfulblade/lawful-create-project.md
  - SoM Hacking:
    - File Formats:
      - Profile:
        - NPC .PRF File Format: editor/ff/prf-npc-file-format.md
      - Sound:
        - .SND File Format: editor/ff/snd-file-format.md
      - Texture:     
        - .TXR File Format: editor/ff/txr-file-format.md
      - Database:
        - Item .PR2 File Format: editor/ff/pr2-item-file-format.md
        - Object .PR2 File Format: editor/ff/pr2-obj-file-format.md
        - NPC .PR2 File Format: editor/ff/pr2-npc-file-format.md
        - Enemy .PR2 File Format: editor/ff/pr2-enemy-file-format.md
        - Effect .DAT File Format: editor/ff/dat-sfx-file-format.md
      - Map:
        - .MPX File Format: editor/ff/map-mpx-file-format.md
  - SomEx Editor: 
    - PlaceHolder: editorex/placeholder.md
  - SoM Games:
    - Installing Games: game/install-games.md
    - Compatibility Fixes: game/comp-games.md
    - Known Bugs: game/bugs-games.md


  - Glossary: glossary.md
extra:
  generator: true
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/66CQdB738d
    - icon: fontawesome/brands/github
      link: https://github.com/Sword-of-Moonlight
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/SwordOfMoonlight
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@SwordofMoonlightCommunity
    - icon: fontawesome/brands/twitter
      link: https://x.com/verditecat
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/swordofmoonlight

theme:
  name: material
  logo: assets/mls.webp
  favicon: assets/favicon.webp
  features:
    - toc.follow
    - toc.integrate 
    - navigation.sections
    - navigation.expand
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Dark Mode      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
plugins:
  #- with-pdf:
      #author: Sword of Moonlight Community
      #copyright: CC0
      #
      #cover: false
      #back_cover: true
      #cover_title: TITLE TEXT
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      #output_path: any-place/document.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
